### ISSUE TITLE
amd64 version?

### ISSUE THREAD

**Issue by ttrepper** [owntone/owntone-apt#1]
Hi all, 
this is a brilliant repo and thank you all very very much for your hard work - but is there any chance you can build an amd64 version as well? 

On http://owntone.github.io/owntone-server/installation/ it says: 
![Bildschirm­foto 2022-12-26 um 11 33 33](https://user-images.githubusercontent.com/3026863/209538938-3d4b949b-d6a8-403c-aed7-c95b0b87185a.jpg)
but here I only find armhf & arm64. Any chance you can build amd64 as well? Thank would be very helpful and much appreciated. 

Thank you very much in advance. 

Thomas

P.S: Or is there an apt-repo somewhere?

**Comment by ejurgensen** [comment]
If you select the latest "Create Debian packages" workflow then you can download an artifact that is called "debian-bullseye-amd64".

There is no apt repo for Debian or Ubuntu that I know of.

**Comment by miniworm** [comment]
@ejurgensen Could you provide way of downloading amd64 deb working currently? Last "Create Debian packages" workflow was over 3 months now so no is expired and there is no way to download artifacts from it.

**Comment by ejurgensen** [comment]
Hi @miniworm, sure, I've triggered a rerun of the build just now. I see Debian amd64 is already ready. I have to look into some way of persisting the builds, I guess they should be release assets.

**Comment by miniworm** [comment]
Thank you @ejurgensen, now I'm able to download deb file. Probably to make it persistent you should add it to release files.
But now I've dependency issues since dep file is for Debian Bullseye but I use Ubuntu 20.04. So during install I have message showing missing libs (no problem) but also libs versions mismatch issue:

sudo dpkg -i ./owntone_28.6.125.gitf9c50b8-1+bullseye_amd64.deb 

Selecting previously unselected package owntone.
(Reading database ... 90688 files and directories currently installed.)
Preparing to unpack .../owntone_28.6.125.gitf9c50b8-1+bullseye_amd64.deb ...
Unpacking owntone (28.6.125.gitf9c50b8-1+bullseye) ...

dpkg: dependency problems prevent configuration of owntone:

 owntone depends on libavcodec58 (>= 7:4.2); however:
  Package libavcodec58 is not installed.
 owntone depends on libavfilter7 (>= 7:4.0); however:
  Package libavfilter7 is not installed.
 owntone depends on libavformat58 (>= 7:4.2); however:
  Package libavformat58 is not installed.
 owntone depends on libavutil56 (>= 7:4.0); however:
  Package libavutil56 is not installed.
 owntone depends on libconfuse2 (>= 3.2.1~); however:
  Package libconfuse2 is not installed.
 owntone depends on libevent-pthreads-2.1-7 (>= 2.1.8-stable); however:
  Package libevent-pthreads-2.1-7 is not installed.
 owntone depends on libgnutls30 (>= 3.7.0); however:
  Version of libgnutls30:amd64 on system is 3.6.13-2ubuntu1.8.
 owntone depends on libjson-c5 (>= 0.15); however:
  Package libjson-c5 is not installed.
 owntone depends on libmxml1 (>= 3.2); however:
  Package libmxml1 is not installed.
 owntone depends on libplist3 (>= 2.2.0); however:
  Version of libplist3:amd64 on system is 2.1.0-4build2.
 owntone depends on libprotobuf-c1 (>= 1.0.1); however:
  Package libprotobuf-c1 is not installed.
 owntone depends on libsodium23 (>= 0.7.0); however:
  Package libsodium23 is not installed.
 owntone depends on libwebsockets16 (>= 2.4.1); however:
  Package libwebsockets16 is not installed.

dpkg: error processing package owntone (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 owntone

**Comment by ejurgensen** [comment]
I thought 20.04 was based on Debian Bullseye, so I'm not sure why this is happening. I can't offer to go into troubleshooting here. Maybe you can try building yourself on Ubuntu, it's fairly straightforward. You can see how here: https://owntone.github.io/owntone-server/building/

For Ubuntu, I would like to find a better distribution method. Something like launchpad, Docker or something else.

**Comment by miniworm** [comment]
In general 20.04 is based on Debian bulllseye but it's not that simple since Debian versions are for a long time in sid state (still in development). So 20.04 was based on bullseye while it was still in sid state. As it shows Debian bumped few libs after 20.04 release (final Debian 11 ''bullseye" was released in April 2021) so in fact Ubuntu 21.10 is first Ubuntu release based on final Debian 11 bullseye (and in fact the last one - starting from 22.04 they switched to Debian 12 bookworm in sid state which ended few days ago with final release so Ubuntu 23.10 will be first Ubuntu release based on final Debian 12 bookworm).

I'll try to build it myself then. My only concern is that build instructions are not for building Debian/Ubuntu package but only to compile binaries and install them "manually" on live system. I'll try to combine both and end with deb package which install without problems and works on Ubuntu 20.04.

**Comment by ejurgensen** [comment]
> I'll try to build it myself then. My only concern is that build instructions are not for building Debian/Ubuntu package but only to compile binaries and install them "manually" on live system

Yes, you are right about that. There isn't a package building guide, but maybe what you could do is clone the owntone-apt repo and then modify the workflow to build for Ubuntu? The workflow uses pbuilder, I assume it might also work for Ubuntu, but haven't actually tried it.
